app_id: 'f1254edd-c8ca-4d97-aa9f-912cb5f2654b'
app_secret: 'Pss8Q~LxSn~PHpiLWNhieTyFzo7gXhACCusKRcIA'
redirect: 'http://localhost:8000/callback'
scopes:
    - user.read
    - mailboxsettings.read
    - calendars.readwrite
authority: 'https://login.microsoftonline.com/agritopper.onmicrosoft.com'
