app_id: 'f1254edd-c8ca-4d97-aa9f-912cb5f2654b'
app_secret: '6f~8Q~EzoMN8AziSZQ2vbfw.OoF..Pwx..6Muai0'
redirect: 'https://crop-report.agritop.net/callback'
scopes:
    - user.read
    - mailboxsettings.read
    - calendars.readwrite
authority: 'https://login.microsoftonline.com/agritopper.onmicrosoft.com'
