# Generated by Django 4.0.3 on 2022-04-13 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plantation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantationdivisionvariety',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantation_division_variety_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='plantationdivisionvariety',
            name='crop_variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantation_cropsvariety', to='plantation.cropvariety', verbose_name='Variedad'),
        ),
        migrations.AddField(
            model_name='plantationdivisionvariety',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantation_division_variety_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='plantationdivisionvariety',
            name='plantation_division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantation_divisionsvariety', to='plantation.plantationdivision', verbose_name='Fundo-Lote'),
        ),
        migrations.AddField(
            model_name='plantationdivision',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantation_division_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='plantationdivision',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantation_division_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='plantationdivision',
            name='plantation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantation_divisions', to='plantation.plantation', verbose_name='Fundo'),
        ),
        migrations.AddField(
            model_name='plantation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_plantations', to='plantation.client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='plantation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantation_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='plantation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_plantations', to='plantation.location', verbose_name='Zona'),
        ),
        migrations.AddField(
            model_name='plantation',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantation_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='ndvitmp',
            name='land_tmp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_ndvis_temps', to='plantation.landtmp'),
        ),
        migrations.AddField(
            model_name='ndvi',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ndvi_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='ndvi',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_ndvis', to='plantation.land', verbose_name='Fundo-División-Variedad'),
        ),
        migrations.AddField(
            model_name='ndvi',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ndvi_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='location',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='location',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='landtmp',
            name='plantation_division_variety_tmp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantationlands_divisionv_variety_temps', to='plantation.plantationdivisionvarietytmp'),
        ),
        migrations.AddField(
            model_name='landinfo',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='land_info_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='landinfo',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='land_info_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='landinfo',
            name='plantation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantation_land_info', to='plantation.plantation', verbose_name='Fundo'),
        ),
        migrations.AddField(
            model_name='land',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='land_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='land',
            name='land_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_land_info', to='plantation.landinfo', verbose_name='Nombre documento'),
        ),
        migrations.AddField(
            model_name='land',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='land_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='land',
            name='plantation_division_variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantationlands_divisionvariety', to='plantation.plantationdivisionvariety', verbose_name='Fundo/Cuartel/Variedad'),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crop_variety_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_varieties', to='plantation.crop', verbose_name='Cultivo'),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='cropVarietySimilar',
            field=models.ManyToManyField(blank=True, to='plantation.cropvariety', verbose_name='Cultivo Similar'),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crop_variety_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='crop',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crop_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='crop',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crop_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='client',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='plantationdivisionvarietytmp',
            unique_together={('unit_me', 'variety', 'plantation')},
        ),
        migrations.AlterUniqueTogether(
            name='ndvitmp',
            unique_together={('color', 'clase', 'min', 'max', 'ha', 'area', 'land_tmp')},
        ),
        migrations.AlterUniqueTogether(
            name='ndvi',
            unique_together={('color', 'clase', 'min', 'max', 'ha', 'area', 'land')},
        ),
        migrations.AlterUniqueTogether(
            name='land',
            unique_together={('plantation_division_variety', 'date', 'kind_proccess', 'days_process')},
        ),
    ]
