# Generated by Django 4.0.3 on 2022-04-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantationdivision',
            name='acronymo_note',
            field=models.CharField(max_length=30, verbose_name='Acrónimo Nota'),
        ),
        migrations.AlterField(
            model_name='plantationdivision',
            name='sub_division_4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sub División [Sólo Ensayos]'),
        ),
        migrations.AlterField(
            model_name='plantationdivisionvariety',
            name='change_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Cambio'),
        ),
    ]
