# Generated by Django 4.0.3 on 2022-04-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantation', '0003_alter_plantationdivision_acronymo_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landinfo',
            name='flight_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero de vuelo'),
        ),
    ]
