# Generated by Django 4.0.3 on 2022-04-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantation', '0004_alter_landinfo_flight_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocPhaseTmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=100, verbose_name='Documento')),
                ('phase_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fase')),
                ('phase_is', models.IntegerField(blank=True, null=True, verbose_name='Fase ID')),
            ],
            options={
                'verbose_name': 'DocPhaseTmp',
                'verbose_name_plural': 'DocPhaseTmps',
                'ordering': ['id'],
            },
        ),
    ]
