# Generated by Django 4.0.3 on 2022-04-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantation', '0005_docphasetmp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='land',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='land',
            name='flight_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero de vuelo'),
        ),
        migrations.AlterUniqueTogether(
            name='land',
            unique_together={('plantation_division_variety', 'date', 'kind_proccess', 'days_process', 'flight_number')},
        ),
    ]
