# Generated by Django 4.0.3 on 2022-04-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantation', '0006_alter_land_unique_together_land_flight_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='land',
            options={'ordering': ['plantation_division_variety__plantation_division__plantation'], 'verbose_name': 'Vuelo [Foto]', 'verbose_name_plural': 'Vuelos [Fotos]'},
        ),
        migrations.AlterField(
            model_name='land',
            name='flight_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de vuelo'),
        ),
    ]
