# Generated by Django 4.0.3 on 2022-04-22 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantation', '0007_alter_land_options_alter_land_flight_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='land',
            unique_together={('plantation_division_variety', 'date', 'kind_proccess', 'days_process')},
        ),
    ]
