# Generated by Django 4.0.3 on 2022-04-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantation', '0008_alter_land_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantationdivision',
            options={'ordering': ['plantation', 'main_division', 'sub_division_1', 'sub_division_2', 'sub_division_3', 'sub_division_4'], 'verbose_name': 'Fundo [Lote]', 'verbose_name_plural': 'Fundos [Lotes]'},
        ),
        migrations.AlterField(
            model_name='crop',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código Interno'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterUniqueTogether(
            name='plantation',
            unique_together={('name', 'client')},
        ),
    ]
