# Generated by Django 4.0.3 on 2022-04-22 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantation', '0009_alter_plantationdivision_options_alter_crop_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landinfo',
            name='flight_number',
        ),
    ]
