# Generated by Django 4.0.3 on 2022-04-25 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantation', '0010_remove_landinfo_flight_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plantationdivision',
            unique_together={('plantation', 'main_division', 'sub_division_1', 'sub_division_2', 'sub_division_3', 'sub_division_4')},
        ),
    ]
