# Generated by Django 4.0.3 on 2022-04-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantation', '0012_alter_plantationdivision_sub_division_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantationdivision',
            name='sub_division_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sub División 1'),
        ),
        migrations.AlterField(
            model_name='plantationdivision',
            name='sub_division_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sub División 2'),
        ),
        migrations.AlterField(
            model_name='plantationdivision',
            name='sub_division_3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sub División 3'),
        ),
        migrations.AlterField(
            model_name='plantationdivision',
            name='sub_division_4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sub División [Sólo Ensayos]'),
        ),
    ]
