# Generated by Django 4.0.3 on 2022-04-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantation', '0013_alter_plantationdivision_sub_division_1_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='plantationdivision',
            constraint=models.UniqueConstraint(fields=('main_division', 'sub_division_1', 'sub_division_2', 'sub_division_3', 'sub_division_4', 'acronymo_note', 'plantation'), name='plantation_plantationdivision_plantation_main_subdivisions_acronymo_uniq'),
        ),
        migrations.AddConstraint(
            model_name='plantationdivision',
            constraint=models.UniqueConstraint(condition=models.Q(('sub_division_1__isnull', True), ('sub_division_2__isnull', True), ('sub_division_3__isnull', True), ('sub_division_4__isnull', True)), fields=('plantation', 'main_division'), name='plantation_plantationdivision_plantation_main_uniq'),
        ),
    ]
