# Generated by Django 4.0.3 on 2022-04-25 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantation', '0014_plantationdivision_plantation_plantationdivision_plantation_main_subdivisions_acronymo_uniq_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plantationdivision',
            name='plantation_plantationdivision_plantation_main_subdivisions_acronymo_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='plantationdivision',
            name='plantation_plantationdivision_plantation_main_uniq',
        ),
    ]
